version: '3.7'

services:
    backend:
        build:
            context: './backend/'
            dockerfile: '/docker/dev'
        container_name: backend_container
        volumes:
            - ./backend/src:/usr/src/app/src
            - ./backend/migrations:/usr/src/app/migrations
        ports:
            - '8080:8080'
        depends_on:
            - postgres
        restart: unless-stopped

    postgres:
        container_name: postgres_container
        image: postgres
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            PGDATA: /data/postgres
        volumes:
            - postgres:/data/postgres
        ports:
            - '5432:5432'
        restart: unless-stopped

    pgadmin:
        container_name: pgadmin_container
        image: dpage/pgadmin4
        environment:
            PGADMIN_DEFAULT_EMAIL: pgadmin4@pgadmin.org
            PGADMIN_DEFAULT_PASSWORD: admin
        volumes:
            - pgadmin:/root/.pgadmin
        ports:
            - '5050:80'
        restart: unless-stopped

volumes:
    postgres:
    pgadmin:
