// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'button': string;
  'danger': string;
  'dark': string;
  'large': string;
  'light': string;
  'link': string;
  'medium': string;
  'outline': string;
  'primary': string;
  'secondary': string;
  'small': string;
  'success': string;
  'tertiary': string;
  'warning': string;
}
export const cssExports: CssExports;
export default cssExports;
