// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'closed': string;
  'open': string;
  'root': string;
}
export const cssExports: CssExports;
export default cssExports;
