import { ColumnDefinitions, MigrationBuilder } from 'node-pg-migrate';

export const shorthands: ColumnDefinitions | undefined = undefined;

export function up(pgm: MigrationBuilder) {
    pgm.sql(
        `CREATE TABLE app_user (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            username TEXT NOT NULL UNIQUE,
            password TEXT NOT NULL,
            created_at TIMESTAMPTZ DEFAULT NOW(),
            updated_at TIMESTAMPTZ DEFAULT NOW()
        )`,
    );

    pgm.sql(
        `CREATE FUNCTION update_updated_at_column()
            RETURNS TRIGGER AS $$
            BEGIN
                NEW.updated_at = now();
                RETURN NEW;   
            END;
            $$ LANGUAGE plpgsql`,
    );

    pgm.sql(
        `CREATE TRIGGER update_app_user_updated_at_column BEFORE UPDATE on app_user FOR EACH ROW EXECUTE PROCEDURE update_updated_at_column()`,
    );
}

export function down(pgm: MigrationBuilder) {
    pgm.sql('DROP TABLE app_user CASCADE');
    pgm.sql('DROP FUNCTION update_updated_at_column');
}
